name: Install SBCL
description: Install SBCL on the target system
inputs:
  version:
    default: false

runs:
  using: composite
  steps:
    - name: Install Linux software
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo "::group::Install Linux software"
        sudo apt-get update
        sudo apt-get install -y sbcl
        echo "::endgroup::"

    - name: Install Windows software
      if: runner.os == 'Windows'
      shell: bash
      run: |
        echo "::group::Install Windows software"
        iwr -useb get.scoop.sh | iex
        scoop install roswell
        ros install sbcl
        ros run
        echo "::endgroup::"
