name: Install SBCL
description: Install SBCL on the target system
inputs:
  version:
    default: false

runs:
  using: composite
  steps:
    - name: Install Linux software
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo "::group::Install Linux software"
        sudo apt-get update
        sudo apt-get install -y sbcl
        echo "::endgroup::"

    - name: Install Windows software
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        echo "::group::Install Windows software"
        iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
        Add-Content $env:GITHUB_PATH "$HOME\scoop\shims"
        scoop install sbcl
        sbcl --help
        echo "::endgroup::"
